// Code generated by BONNIE (bonnie build / bonnie dev). DO NOT EDIT.
//
// bonnie_gen.go is disposable: delete it and regenerate. Every other file in
// this tree is authored and BONNIE never rewrites it. Discovery walks
// tools/<name>/tool.go; each directory exports func Tool() kit.Tool and the
// directory name is the tool's name.
package main

import (
	"embed"

	"github.com/mark3labs/bonnie"
	kit "github.com/mark3labs/kit/pkg/kit"
)

//go:embed instructions.md
var _instructions string

var _skills embed.FS

var _workspace embed.FS

// init hands the tree's discovered code and embedded data to the runtime
// before main runs, so main.go never has to name a tool or an embed. Each
// tools/<name>/tool.go exports func Tool() kit.Tool.
func init() {
	bonnie.Register(bonnie.Tree{
		Instructions: _instructions,
		Skills:       _skills,
		Workspace:    _workspace,
		Tools:        []kit.Tool{},
	})
}
